### ISSUE TITLE
How to generate a file like "NATOPS_TRAIN.arff"

### ISSUE THREAD

**Issue by XuZhao-design** [ai-fast-track/timeseries#3]
Thank you for the detailed introduction! "TSData.from_arff()" is an awesome function which can be used to read arff file. However, I am not sure how to generate a file like "NATOPS_TRAIN.arff". I know how to convert my data to the file like "NATOPSDimension1_Train.arff", which only contains one dimension. How can I combine different dimensions together?  Thank you!

**Comment by ai-fast-track** [comment]
You might check out this video tutorial on how to create an `.arrf` file. You can ignore the second part of the tutorial about WEKA:

[Creating ARFF Files for Weka](https://www.youtube.com/watch?v=QtNYArb0Tkc)

**Comment by XuZhao-design** [comment]
> You might check out this video tutorial on how to create an `.arrf` file. You can ignore the second part of the tutorial about WEKA:
> 
> [Creating ARFF Files for Weka](https://www.youtube.com/watch?v=QtNYArb0Tkc)

Thank you so much! I have solved the problem!

**Comment by i-Corner** [comment]
Maybe you can download here [link](https://timeseriesclassification.com/description.php?Dataset=NATOPS)
